### ISSUE TITLE
Nodejs example

### ISSUE THREAD

**Issue by rooi** [patlux/node-cec#1]
Hi,

Looks like a nice project. Thanks for sharing!

I would like to create a homebridge-cec plugin to control my equipment using apple's homekit and siri. Do you have an node.js example of how one can use this project?

The code you have included isn't js right?

Thanks!

Roy

**Comment by patlux** [comment]
Hi,

sorry for the late response. Yeah you're right, that was coffeescript. I have now added an example in javascript.

~ patlux

**Comment by rooi** [comment]
Thx!

I've managed to create a first version of homebridge-cec to control my tv using apple's homekit through siri. If you'd like you can have a look at: https://github.com/rooi/homebridge-cec

I think I still want to kill possible old cec-client processes and do some other optimizations, but the  first version works.

Thanks for sharing and your help!
