### ISSUE TITLE
sending command examples

### ISSUE THREAD

**Issue by santiDotIO** [patlux/node-cec#5]
Hi, can you provide some example of sending command, or explain a little more? for example sending input change commands etc.

**Comment by patlux** [comment]
To be honest: I don't know if its possible to change the input source programmatically. Maybe its possible when you send a "fake"-wakeup command to the tv, the tv should then change its input source to the new source.

See http://www.cec-o-matic.com/:
![2017-03-06-212622_1776x721_scrot](https://cloud.githubusercontent.com/assets/4481570/23628129/9eb5ddac-02b3-11e7-82c2-b354db4303ef.jpg)

**Comment by santiDotIO** [comment]
I been playing with this library, first off thank you so much for creating it!
I think what would help if there was better documentation of the methods avaliblee. For example, in your [basic.js](https://github.com/patlux/node-cec/blob/master/examples/basic.js#L30) you have an example of `client.sendCommand` which hints that it's only usable inside the ready callback

but looking at the source code `client` is just an instance of `cec` vairable.

Also the `.send ` method should be documented. While most commands you send with `tx xx:xx:xx` you can send other commands with cec like `scan` and `sendCommand` prefixes the tx

**Comment by santiDotIO** [comment]
Also the different listener I notice a few are handled differently 
https://github.com/patlux/node-cec/blob/master/src/node-cec.coffee#L137-L154
or how their event listeners for all Opcode
